#!/usr/bin/env ruby
#
#  pass_server_ctl
#  Pass Server reference implementation
#

#!/usr/env ruby
require 'rubygems'
require 'sequel'
require 'sequel/extensions/pretty_table'
require 'open-uri'
require 'json'
require 'fileutils'
require 'optparse'



class ServerSetup
  attr_accessor :db, :db_file, :hostname, :port, :pass_type_identifier, :team_identifier
  
  def initialize
    self.db_file =  File.dirname(File.expand_path(__FILE__)) + "/../data/pass_server.sqlite3"
  end
    

  

  
  def setup_database
    # Create an empty database file
    if !File.exists?(self.db_file)
      File.open(self.db_file, "w"){}
    end
  end
  
  def open_database
    # Open the database
    self.db = Sequel.sqlite(self.db_file)
    puts "Loading the database file"
  end
  
  def create_passes_table
    # Create the Passes table
    if !self.db.table_exists?(:passes)
      puts "Creating the passes table"
      self.db.create_table :passes do
        primary_key :id
        String :serial_number
        String :authentication_token
        String :pass_type_id
        Integer :updated_at
      end
    end
  end
  
  def create_registrations_table
    # Create the registrations table
    if !self.db.table_exists?(:registrations)
      puts "Creating the registrations table"
      self.db.create_table :registrations do
        primary_key :id
        String :uuid
        String :device_id
        String :push_token
        String :serial_number
        String :pass_type_id
      end
    end
  end
  

  
  

  
end


options = {}
optparse = OptionParser.new do |opts|
  
 
  
  options[:setup] = false
  opts.on("-s", "--setup", "Setup the pass server") do |s|
    options[:setup] = s
  end
  
 
  
  # options[:start_server] = false
  # opts.on("server", "Starts the webserver on port 4567") do |s|
  #   options[:start_server] = s
  # end
  
  
  opts.on('-h', '--help', 'Display this screen') do 
    puts opts
    exit
  end
  
end

optparse.parse!
if options[:setup]
  reference_server_setup = ServerSetup.new
  reference_server_setup.setup_database
  reference_server_setup.open_database
  reference_server_setup.create_passes_table
  reference_server_setup.create_registrations_table
  puts "Reference server setup complete."
end













